### zeros() : 괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화

In [19]:
import numpy as np

y = np.zeros(shape=(10,2), dtype=np.int8)
#y = np.zeros(10)
y

#x = np.array([1,2,3]) #[1,2,3]은 리스트인데 이 리스트를 배열로 만들어주는 매소드
#type(x)
#x.shape


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

### mean() : 배열에 저장된 원소들의 평균값을 계산

In [23]:
import numpy as np

list_1 = [1,2,3]
x = np.array(list_1)
np.mean(x)
x.mean()

2.0

In [22]:
list_1 = [1,2,3]
x = np.array(list_1)
x.shape

(3,)

#### array(): Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력

In [32]:
x = np.array([1,2,3])
y = np.array((1,2,3))
z = np.array({12,3,4})
a = np.array({"a":"b", "a":"c"}) #같은 값이 있다면 항상 마지막 값이 출력되는 딕셔너리의 성질
print(x,y,z,a)

[1 2 3] [1 2 3] {3, 12, 4} {'a': 'c'}


#### reshape(): 배열을 원하는 모양으로 생성

In [123]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b, b.shape)
print(c, c.shape)
#print(c)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


#### reshape() 응용: 3차원 만들기

In [39]:
a = np.arange(1, 9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
b = a.reshape(2,2,2)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
a = np.arange(1, 13)
print(a)
b = a.reshape(3,2,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


##### reshape 의미

###### reshape를 활용하는 경우를 보다 보면 입력인수로 -1이 들어간 경우가 종종 있다. reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [47]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [54]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

#### ones() : 배열을 1의 값들로 채움

In [61]:
y = np.ones([4,3])
#z = y*0.3
print(y)
#print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Numpy 배열의 슬라이싱


In [64]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
print(list1[:][1])
print(list1[:,1])

[2, 12]


TypeError: list indices must be integers or slices, not tuple

In [80]:
list1 = [[1,11],[2,12],[3,13],[4,14]]
arr = np.array(list1)
print(arr)
print(arr.shape)
print(arr[:,1])
print(arr[:][1])
print(arr[1][1])
print(arr[1:3][1])
print(arr[1:4])

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]]
(4, 2)
[11 12 13 14]
[ 2 12]
12
[ 3 13]
[[ 2 12]
 [ 3 13]
 [ 4 14]]


#### math 모듈 이용의 sqrt()와 numpy 모듈의 sqrt() 비교

In [83]:
import math
math.sqrt(2)
math.sqrt([2,3,4]) #math는 각각의 원소에게 루트를 씌울 수 없음

TypeError: must be real number, not list

In [84]:
import numpy as np
np.sqrt(2)
np.sqrt([2,3,4]) #하지만 numpy는 리스트 안의 원소에 각각 루트를 씌울 수 있음

array([1.41421356, 1.73205081, 2.        ])

In [88]:
import numpy as np

x = np.zeros(15)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
y = np.zeros([5,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [125]:
#(3,5) 형태로 reshape
y = np.zeros([5,3])
z = y.reshape([3,5])

#원소를 4로 지정한 (3,5)행렬을 만들어라
z += 4
print(z)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


### 전치행렬
#### transpose() : 행과 열을 교환하여 얻어지는 행렬, 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미

In [95]:
import numpy as np

list = [[1,2],[3,4]]
ary = np.array(list)
print(ary)
print('\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]]


[[1 3]
 [2 4]]


In [97]:
ary = np.array([[1,2,5],[3,4,6]])
print(ary)
print('\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2 5]
 [3 4 6]]


[[1 3]
 [2 4]
 [5 6]]


#### 2개 배열에 대한 연산
###### – 2개 배열에 저장된 내용을 인덱스별로 계산
###### – 선형대수학의 사칙연산과 동일하게 작동. 곱셈도 같은 원리로 동작

In [103]:
import numpy as np

x = np.array((3,4,5))
y = np.array((1,2,3))
print(x+y)
print(x*y)
print(x%y)
print(x**y)

[4 6 8]
[ 3  8 15]
[0 0 2]
[  3  16 125]


In [110]:
x = np.array((3,4,5))
x += 15
print(x)

[18 19 20]


#### 인덱싱

In [114]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:, 1])

[4 5 6]
[2 5 8]


#### 2개의 numpy 배열 간의 계산

In [121]:
#x의 1행과 y의 3행을 더한 값을 출력하시오
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[2,3,4], [5,6,7], [8,9,10]])
print(x[0,:]+y[2,:])
print(x[0]+y[2])

[ 9 11 13]
[ 9 11 13]


In [126]:
#x의 2열과 y의 3행을 곱한 값을 출력하시오
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[2,3,4], [5,6,7], [8,9,10]])
print(x[:,1]*y[2])

[16 45 80]


In [127]:
a = np.array([10,20,30,40,60])
b = a>30
print(b)

[False False False  True  True]


#### random()

In [135]:
import numpy as np

ary = np.random.random(5)
print(ary)

[0.0938272  0.46528454 0.31092848 0.59773829 0.62223339]
[[[0.53656776 0.19773886]
  [0.91591733 0.35763205]
  [0.27669952 0.13160736]]

 [[0.44099669 0.59547045]
  [0.92952941 0.44068452]
  [0.83202923 0.6498491 ]]] (2, 3, 2)


In [145]:
# (0,1) 범위에서 균일한 분포
ary = np.random.random(5)
print(ary)

b = np.random.rand(2, 3, 2)   #rand를 쓰면 행렬을 만들어준다
print(b, b.shape)

[0.1622699  0.08440307 0.03478815 0.25458932 0.30927639]
[[[0.78038541 0.18814687]
  [0.05196056 0.43891318]
  [0.98282512 0.61276254]]

 [[0.21445824 0.46434165]
  [0.90153103 0.04241003]
  [0.1711839  0.49692842]]] (2, 3, 2)


In [142]:
a = np.random.randint(2, size=5)
print(a)

b = np.random.randint(2, 4, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[0 0 1 1 0]
[3 3 3 2 3]
[[3 2 1]
 [2 1 4]]


#### random.seed() : 함수는 난수 생성에 필요한 시드를 설정합니다.

In [146]:
np.random.seed(0)
print(np.random.rand(2,3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


In [163]:
np.random.seed(0)
a = np.random.random(5)
#a>0.12
print(a>0.12)
print(np.all(a>0.12))

[ True  True  True  True  True]
True


#### any() 와 all() 의 비교

In [168]:
a = np.random.random(5)
print(a>0.12)
np.all(a>0.12)

[ True  True  True  True  True]


True

In [193]:
a = np.random.random(5)
print(a>0.9)
np.any(a>0.9)

[False False False False False]


False

#### linspace() : 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분

In [196]:
np.linspace(0, 12, 4)

array([ 0.,  4.,  8., 12.])

In [197]:
np.linspace(0, 12, 4, endpoint=False) #마지막 값을 제외하고 샘플값을 만들어냄

array([0., 3., 6., 9.])

In [199]:
np.linspace(0, 12, 4, retstep=True) #간격이 되는 숫자값을 도출해줌

(array([ 0.,  4.,  8., 12.]), 4.0)